auth:
    jwt:
        expires: '90000s'
database:
    mongodb:
        connection: 'mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL_CONNECTION}${MONGODB_DATABASE_NAME}${MONGODB_SUFIX_PARAMS}'
        url: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}/${RABBITMQ_VHOST}'
        queue:
            connection: 'places-connection'
            seed:
                neighborhoods:
                    by:
                        city:
                            process: 'seed-neighborhoods-by-city-process'
                            success: 'seed-neighborhoods-by-city-success'
                            error: 'seed-neighborhoods-by-city-error'
                        state:
                            process: 'seed-neighborhoods-by-state-process'
        exchange:
            seed:
                neighborhoods:
                    by:
                        city:
                            process: 'seed-neighborhoods-by-city-process'
                            success: 'seed-neighborhoods-by-city-success'
                            error: 'seed-neighborhoods-by-city-error'
                        state:
                            process: 'seed-neighborhoods-by-state-process'
        channel:
            prefetch-count: 1
            seed:
                neighborhoods:
                    by:
                        city: 'channel-seed-neighborhoods-by-city'
                        state: 'channel-seed-neighborhoods-by-state'
api:
    port: 5000
doc:
    version: 1.0.0
    name: 'auth'
