export enum EnumAuthScopes {
    ADM_SCOPE = 'AUTH/API/ADM',
    CREATE_USER = 'AUTH/API/CREATE_USER',
    CREATE_SCOPE = 'AUTH/API/CREATE_SCOPE',
    GRANT_SCOPE = 'AUTH/API/GRANT_SCOPE',
    UPDATE_PASSWORD = 'AUTH/API/UPDATE_PASSWORD',
    FORGOT_PASSWORD = 'AUTH/API/FORGOT_PASSWORD',
    GET_PROJECT = 'AUTH/API/GET_PROJECT',
    GET_USER = 'AUTH/API/GET_USER',
    GET_SCOPE = 'AUTH/API/GET_SCOPE',
    ACTIVATE_USER = 'AUTH/API/ACTIVATE_USER',
    INACTIVATE_USER = 'AUTH/API/INACTIVATE_USER',
    UPDATE_USER = 'AUTH/API/UPDATE_USER',
    CREATE_PROJECT = 'AUTH/API/CREATE_PROJECT'
}
