export enum EnumAuthScopes {
    CREATE_USER = 'AUTH/API/CREATE_USER',
    CREATE_SCOPE = 'AUTH/API/CREATE_SCOPE',
    GRANT_SCOPE = 'AUTH/API/GRANT_SCOPE',
    UPDATE_PASSWORD = 'AUTH/API/UPDATE_PASSWORD',
    FORGOT_PASSWORD = 'AUTH/API/FORGOT_PASSWORD',
    ADM_SCOPE = 'AUTH/API/ADM'
}
